// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzrmmqusiknbmsywudbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6cm1tcXVzaWtuYm1zeXd1ZGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjkyMDksImV4cCI6MjA2NjIwNTIwOX0.cnESsBdJqdA9bb692eimzyPGFb7WtiWQtoe4RxMBxlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);